version: '2'

services:
    elasticsearch:
        build: ./.docker/elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"

    kibana:
        build: ./.docker/kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch
