version: '2'

services:
    elasticsearch:
        build: ./.docker/elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - "./data:/usr/share/elasticsearch/data"

    kibana:
        build: ./.docker/kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch
