version: '2'

services:
    elasticsearch:
        build: ./.docker/elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - "./.docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
            - "./.docker/elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options"
            - "./.docker/elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml"
            - "./.docker/elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
            - "./data:/usr/share/elasticsearch/data"

    kibana:
        build: ./.docker/kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch
        volumes:
            - "./.docker/kibana/config:/usr/share/kibana/config"

    logstash:
        build: ./.docker/logstash
        volumes:
            - "./sample:/tmp/data/"
        ports:
            - "5044:5044"
        links:
            - elasticsearch