version: '3'

services:
    elasticsearch:
        build: ./.docker/elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - "./data:/usr/share/elasticsearch/data"

    kibana:
        build: ./.docker/kibana
        volumes:
            - "./.docker/kibana/config:/kibana/config"
        ports:
            - "5601:5601"
        links:
            - elasticsearch

    logstash:
        build: ./.docker/logstash
        volumes:
            - "./sample:/tmp/data/"
        ports:
            - "5044:5044"
        links:
            - elasticsearch