# you can override this using by setting a system property, for example -Des.logger.level=DEBUG
es.logger.level: INFO
rootLogger: ${es.logger.level}, console
logger:
  # log action execution errors for easier debugging
  action: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"



index.search.slowlog.threshold.query.warn: 0s
index.search.slowlog.threshold.query.info: 0s
index.search.slowlog.threshold.query.debug: 0s
index.search.slowlog.threshold.query.trace: 0s

index.search.slowlog.threshold.fetch.warn: 0s
index.search.slowlog.threshold.fetch.info: 0s
index.search.slowlog.threshold.fetch.debug: 0s
index.search.slowlog.threshold.fetch.trace: 0s

index.indexing.slowlog.threshold.index.debug: 0s

index.search.slowlog.level: info